# Generated by Django 4.0.4 on 2022-04-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_CUSTOMER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='客名', max_length=200)),
                ('customer_valid_flg', models.BooleanField(default=True, help_text='有効フラグ（Trueで有効）')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='M_PAYMENT_KIND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_kind_name', models.CharField(help_text='支払い種別名', max_length=200)),
                ('payment_kind_valid_flg', models.BooleanField(default=True, help_text='有効フラグ（Trueで有効）')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='T_PAYMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_kind_id', models.CharField(help_text='支払い種別id', max_length=200)),
                ('bank_name', models.CharField(help_text='取引銀行名', max_length=200)),
                ('payment_money', models.CharField(help_text='支払い、振り込み金額', max_length=200)),
                ('payment_valid_flg', models.BooleanField(default=True, help_text='有効フラグ（Trueで有効）')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新日時')),
                ('customer_id', models.ForeignKey(help_text='客ID', on_delete=django.db.models.deletion.CASCADE, to='polls.m_customer')),
            ],
        ),
    ]
