# Generated by Django 4.0.4 on 2022-04-23 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_payment',
            name='payment_kind_id',
            field=models.ForeignKey(help_text='支払い種別id', on_delete=django.db.models.deletion.CASCADE, to='polls.m_payment_kind'),
        ),
    ]
