# Generated by Django 4.0.4 on 2022-05-25 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_t_payment_payment_kind_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 15, 49, 42, 814629, tzinfo=utc), help_text='支払い日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_payment',
            name='payment_memo',
            field=models.CharField(default='test', help_text='memo', max_length=2000),
            preserve_default=False,
        ),
    ]
